<?php
namespace common\widgets\rightColumn;

use common\models\Category;
use yii\bootstrap\Widget;

class RightColumn extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $categories = Category::find()->Where(Category::tableName() . '.`status` = 1')->all();
        echo $this->render('layout', [
            'categories' => $categories
        ]);
    }
}