<?php
namespace common\widgets\rightColumn;

use common\models\Category;
use yii\bootstrap\Widget;

class RightColumn extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $categories = Category::find()->all();
        echo $this->render('layout',[
            'categories'=>$categories
        ]);
    }
}