<?php
namespace common\widgets\similar;

use yii\bootstrap\Widget;


class SimilarWidget extends Widget
{
    public $categoryId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        echo $this->render('layout');
    }
}