<?php
namespace common\widgets\coments;

use yii\bootstrap\Widget;

class ComentWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        echo $this->render('layout');
    }
}
