<?php
namespace common\widgets\coments;

use common\models\Comment;
use yii\bootstrap\Widget;

class ComentWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run();
        $comments = new Comment();
        $data['comments'] = $comments->getNewComments();
        $data['count'] = count($data['comments']);
        $data['countText'] = \Yii::t('app', 'У вас {n, plural, one{# новый коментарий} few{# новых коментарий} many{# новых коментарий} other{# новых коментария}}', ['n' => $data['count']]);

        echo $this->render('layout', [
            'data' => $data
        ]);
    }
}
