<?php
namespace common\widgets\posts;

use common\models\Comment;
use common\models\Post;
use yii\bootstrap\Widget;

class PostsWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run();
        $posts = new Post();
        $data['posts'] = $posts->getNewPosts();
        $data['count'] = count($data['posts']);
        $data['countText'] = \Yii::t('app', 'У вас {n, plural, one{# новый пост} few{# новых постов} many{# новых постов} other{# новых поста}}', ['n' => $data['count']]);

        echo $this->render('layout', [
            'data' => $data
        ]);
    }
}
